rootProject.name = "Shuvi"
include("service")
include("service-hello")
include("database")
include("database-mongo")
include("service-device")
include("repository")
include("repository-device")
include("repository-hello")
include("entity")
include("service-device-create")
include("repository-device-create")
